- .gitignore
- gateway.go
- init.go
For https://github.com/ipfs/go-ipfs/pull/4595#issuecomment-416738416
No fs-repo migration needed.
> Add Gateway.APICommands for /api allowlists

- addresses.go
- init.go
- profile.go
- types.go
Alternative to #6 that doesn't require a migration. This is probably a terrible idea.
> allow multiple API/Gateway addresses

- types.go
Of course `null` (what an empty array marshals to) cast to a string, is an empty string. This fix prevents us from e.g. ending up with empty multiaddrs.
> Fix handling of null strings

- .gx/lastpubver
- package.json
- swarm.go
Necessary for https://github.com/ipfs/go-ipfs/pull/5785
> autorelay options

- init.go
Fix for: https://github.com/ipfs/go-ipfs/issues/5138
License: MIT
Signed-off-by: Ivan <ivan386@users.noreply.github.com>
> Allow the use of the User-Agent header

- config.go
- config_test.go
- types_test.go
The user must call this before modifying the config. Given that the config contains slices/maps modifications can modified *shared* state, even after dereferencing.
(also adds some tests I failed to commit in my Strings-type PR)
> add a Clone function

- experiments.go
After merging, please add a release tag, so I can use this from go-ipfs. (I don't have write access to any of the IPFS repositories).
> add an experiment to prefer TLS 1.3 over secio

- config.go
- init.go
- plugins.go
* Allow users to store plugin specific config options.
* Allow users to disable specific plugins.
Eventually, we can use this to allow loading plugins from non-standard locations.
> add plugins config section

- plugins.go
Turns out the go-ipfs config logic really doesn't play well with this. Let's just keep them and avoid encoding empty values another way.
> plugins: don't omit empty config values

- profile.go
Per https://github.com/ipfs/go-ipfs/issues/6775 this turns off sync writes in badger by default
> profile: badger profile now defaults to asynchronous writes

- README.md
- routing.go
That way, users can enable/disable/configure routing on their local network.
> feat: add private routing config field

- routing.go
This can't be set independently at this point. We can add something back when we
know the form this option should take.
> feat: remove Routing.PrivateType

- autonat.go
- config.go
- swarm.go
And remove the current EnableAutoNATService option from the swarm config. While a breaking change, this shouldn't cause _too_ much trouble given that we're going to enable AutoNAT everywhere by default anyways.
> feat: add an autonat config section

- pubsub.go
It's still possible to disable signing. However, it's no longer possible to enable signing _and_ disable strict signature verification.
> feat: remove strict signing pubsub option.

- bootstrap_peers.go
- init.go
fixes 1) of https://github.com/ipfs/go-ipfs/issues/7343
> default config: add QUIC listening ports + quic to mars.i.ipfs.io

- config.go
- peering.go
for https://github.com/ipfs/go-ipfs/pull/7362
> feat: add peering service config section

- experiments.go
We should have a more permanent way to configure security transports, but experimental flags are a quick and unstable way to do this without making any promises.
> feat: add an option for security transport experiments

- serialize/serialize.go
There's no reason to give the group access to these files by default.
> fix: remove group permissions

- init.go
- profile.go
This is needed for the upcoming release since there is not yet an official badger2 release with the items needed for use by IPFS.
> Remove badger2 profile

- bootstrap_peers.go
- config.go
- remotepin.go
This is needed for https://github.com/ipfs/go-ipfs/pull/7661
> add remote pinning services config

- init.go
- remotepin.go
Needed for https://github.com/ipfs/go-ipfs/pull/7798
Part of https://github.com/ipfs/go-ipfs/issues/7559 / https://github.com/ipfs/ipfs-gui/issues/91
> add support for pinning mfs

- config.go
- init.go
- migration.go
- migration_test.go
Adds a configuration section `Migration` to configure how to download repo migrations and whether or not to keep them.
> Add config for downloading repo migrations

- bootstrap_peers.go
> error strings should not end with punctuation or a newline (ST1005)
https://deepsource.io/gh/grafov/m3u8/issue/SCC-ST1005/occurrences
> remove period, fix staticcheck

- init.go
> fix: remove deprecated calls

- config.go
- internal.go
- types.go
- types_test.go
Adding:
* Internal.Bitswap.EngineBlockstoreWorkerCount
* Internal.Bitswap.TaskWorkerCount
* Internal.Bitswap.EngineTaskWorkerCount
* Internal.Bitswap.MaxOutstandingBytesPerPeer
Part of https://github.com/ipfs/go-ipfs/issues/8233
Includes #142
> Add internal knobs for Bitswap tuning

- internal.go
- profile.go
- swarm.go
- types.go
- types_test.go
- Need this for https://github.com/ipfs/go-ipfs/pull/8522
- circuit v2: https://github.com/libp2p/specs/blob/master/relay/circuit-v2.md
@vyzo How should we expose configuration options for the limited relay? Should we have a `RelayConfig` that mirrors https://github.com/libp2p/go-libp2p/blob/4f129401a3e4828eaec6818e5a2a1a8f9db1bd8c/p2p/protocol/circuitv2/relay/resources.go#L7-L41?
> feat: Swarm.RelayService (circuit v2)

- swarm.go
The tricky part of this will be the logic how we enable this:
- For this release, we enable hole punching if AutoRelay is enabled.
- For the next release (when the network has an army of relay nodes), we enabled this by default.
> add a flag to enable the hole punching service

- experiments.go
Given that we switch to autosharding setup in https://github.com/ipfs/go-ipfs/pull/8527,  we should deprecate this flag, making it optional in JSON.
> chore: omitempty Experimental.ShardingEnabled

- swarm.go
> Needed for https://github.com/ipfs/go-ipfs/pull/8559
Unfortunately, semver will probably force us to release this as v0.18.0.
> feat: omitempty Swarm.EnableRelayHop for circuit v1 migration

- dns.go
* Add an optional parameter to set a maximum TTL for DNS-over-HTTPS resolver
This is going to be used to expose `WithMaxCacheTTL` option of go-doh-resolver, which release is tracked in https://github.com/libp2p/go-doh-resolver/issues/15.
> feat: Add DNS.MaxCacheTTL for DNS-over-HTTPS resolvers

- profile.go
This is copy-paste from https://github.com/ipfs/go-ipfs/pull/8662 to ensure consistency.
> docs: updated flatfs/badger profile helptext
